
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Daniela
 */
public class KinoJFrame extends javax.swing.JFrame {
    private Kinosal kinosal=new Kinosal();
    /**
     * Creates new form KinoJFrame
     */
    public KinoJFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        platno_JPanel = new Platno(kinosal);
        ulozit_JButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sedadla v kině");

        platno_JPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                platno_JPanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout platno_JPanelLayout = new javax.swing.GroupLayout(platno_JPanel);
        platno_JPanel.setLayout(platno_JPanelLayout);
        platno_JPanelLayout.setHorizontalGroup(
            platno_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        platno_JPanelLayout.setVerticalGroup(
            platno_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        ulozit_JButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ulozit_JButton.setText("uložit");
        ulozit_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulozit_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(ulozit_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(platno_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(platno_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ulozit_JButton)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void platno_JPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_platno_JPanelMousePressed
       //inicializace změny barev        
        kinosal.klikni(evt.getX(), evt.getY());
      platno_JPanel.repaint();
    }//GEN-LAST:event_platno_JPanelMousePressed

    private void ulozit_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulozit_JButtonActionPerformed
       
    JFileChooser jFileChooser = new JFileChooser();
    jFileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
        @Override
        public boolean accept(File f) {
            return f.getName().toLowerCase().endsWith(".txt")||f.isDirectory();
        }
        @Override
        public String getDescription() {
            return "Textové soubory (*.txt)";
        }
    });
    int vysledek = jFileChooser.showSaveDialog(this);
    if (vysledek == JFileChooser.APPROVE_OPTION) {
        String cesta = jFileChooser.getSelectedFile().getAbsolutePath();
        try {
            kinosal.uloz(cesta + ".txt");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Chyba: " + ex.getMessage());
        }
    }

       
    }//GEN-LAST:event_ulozit_JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KinoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KinoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KinoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KinoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                KinoJFrame kinoJFrame = new KinoJFrame();
                kinoJFrame.setLocationRelativeTo(null);
                kinoJFrame.setVisible(true);
                
                ImageIcon icon = new ImageIcon(getClass().getResource("/clovek.png"));
                kinoJFrame.setIconImage(icon.getImage());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel platno_JPanel;
    private javax.swing.JButton ulozit_JButton;
    // End of variables declaration//GEN-END:variables
}
